version: '2.1'

services:
    main-gitbucket:
      image: pgollor/gitbucket
      restart: always
      volumes:
        - ./data/repositories:/srv/gitbucket/repositories
        - ./data/data.mv.db:/srv/gitbucket/data.mv.db
        - ./data/gitbucket.conf:/srv/gitbucket/gitbucket.conf
      ports:
        - "${GITBUCKET_BIND:-127.0.0.1}:${GITBUCKET_WEB_PORT:-8080}:8080"
        - "${GITBUCKET_BIND:-127.0.0.1}:${GITBUCKET_SSH_PORT:-29418}:29418"
